fileExtensions:
  - php
mappings:
  ArrayList: SilverStripe\ORM\ArrayList
  DatabaseAdmin: SilverStripe\ORM\DatabaseAdmin
  DataExtension: SilverStripe\ORM\DataExtension
  DataList: SilverStripe\ORM\DataList
  DataModel: SilverStripe\ORM\DataModel
  DataObject: SilverStripe\ORM\DataObject
  DataObjectInterface: SilverStripe\ORM\DataObjectInterface
  DataObjectSchema: SilverStripe\ORM\DataObjectSchema
  DataQuery: SilverStripe\ORM\DataQuery
  DataQuery_SubGroup: SilverStripe\ORM\DataQuery_SubGroup
  DB: SilverStripe\ORM\DB
  SS_Filterable: SilverStripe\ORM\SS_Filterable
  GroupedList: SilverStripe\ORM\GroupedList
  HasManyList: SilverStripe\ORM\HasManyList
  HiddenClass: SilverStripe\ORM\HiddenClass
  SS_Limitable: SilverStripe\ORM\SS_Limitable
  SS_List: SilverStripe\ORM\SS_List
  SS_ListDecorator: SilverStripe\ORM\SS_ListDecorator
  ManyManyList: SilverStripe\ORM\ManyManyList
  SS_Map: SilverStripe\ORM\SS_Map
  SS_Map_Iterator: SilverStripe\ORM\SS_Map_Iterator
  PolymorphicHasManyList: SilverStripe\ORM\PolymorphicHasManyList
  SilverStripe\Model\Relation: SilverStripe\ORM\Relation
  RelationList: SilverStripe\ORM\RelationList
  SS_Sortable: SilverStripe\ORM\SS_Sortable
  UnsavedRelationList: SilverStripe\ORM\UnsavedRelationList
  ValidationException: SilverStripe\ORM\ValidationException
  ValidationResult: SilverStripe\ORM\ValidationResult
  SQLAssignmentRow: SilverStripe\ORM\Queries\SQLAssignmentRow
  SQLConditionalExpression: SilverStripe\ORM\Queries\SQLConditionalExpression
  SQLConditionGroup: SilverStripe\ORM\Queries\SQLConditionGroup
  SQLDelete: SilverStripe\ORM\Queries\SQLDelete
  SQLExpression: SilverStripe\ORM\Queries\SQLExpression
  SQLInsert: SilverStripe\ORM\Queries\SQLInsert
  SQLSelect: SilverStripe\ORM\Queries\SQLSelect
  SQLUpdate: SilverStripe\ORM\Queries\SQLUpdate
  SQLWriteExpression: SilverStripe\ORM\Queries\SQLWriteExpression
  SS_Database: SilverStripe\ORM\Connect\SS_Database
  SS_DatabaseException: SilverStripe\ORM\Connect\SS_DatabaseException
  DBConnector: SilverStripe\ORM\Connect\DBConnector
  DBQueryBuilder: SilverStripe\ORM\Connect\DBQueryBuilder
  DBSchemaManager: SilverStripe\ORM\Connect\DBSchemaManager
  MySQLDatabase: SilverStripe\ORM\Connect\MySQLDatabase
  MySQLiConnector: SilverStripe\ORM\Connect\MySQLiConnector
  MySQLQuery: SilverStripe\ORM\Connect\MySQLQuery
  MySQLQueryBuilder: SilverStripe\ORM\Connect\MySQLQueryBuilder
  MySQLSchemaManager: SilverStripe\ORM\Connect\MySQLSchemaManager
  MySQLStatement: SilverStripe\ORM\Connect\MySQLStatement
  PDOConnector: SilverStripe\ORM\Connect\PDOConnector
  PDOQuery: SilverStripe\ORM\Connect\PDOQuery
  SS_Query: SilverStripe\ORM\Connect\SS_Query
  DBBoolean: SilverStripe\ORM\FieldType\DBBoolean
  DBClassName: SilverStripe\ORM\FieldType\DBClassName
  DBComposite: SilverStripe\ORM\FieldType\DBComposite
  DBCurrency: SilverStripe\ORM\FieldType\DBCurrency
  DBDate: SilverStripe\ORM\FieldType\DBDate
  DBDatetime: SilverStripe\ORM\FieldType\DBDatetime
  DBDecimal: SilverStripe\ORM\FieldType\DBDecimal
  DBDouble: SilverStripe\ORM\FieldType\DBDouble
  DBEnum: SilverStripe\ORM\FieldType\DBEnum
  DBField: SilverStripe\ORM\FieldType\DBField
  DBFloat: SilverStripe\ORM\FieldType\DBFloat
  DBForeignKey: SilverStripe\ORM\FieldType\DBForeignKey
  DBHTMLText: SilverStripe\ORM\FieldType\DBHTMLText
  DBHTMLVarchar: SilverStripe\ORM\FieldType\DBHTMLVarchar
  DBInt: SilverStripe\ORM\FieldType\DBInt
  DBLocale: SilverStripe\ORM\FieldType\DBLocale
  DBMoney: SilverStripe\ORM\FieldType\DBMoney
  DBMultiEnum: SilverStripe\ORM\FieldType\DBMultiEnum
  DBPercentage: SilverStripe\ORM\FieldType\DBPercentage
  DBPolymorphicForeignKey: SilverStripe\ORM\FieldType\DBPolymorphicForeignKey
  DBPrimaryKey: SilverStripe\ORM\FieldType\DBPrimaryKey
  DBString: SilverStripe\ORM\FieldType\DBString
  DBText: SilverStripe\ORM\FieldType\DBText
  DBTime: SilverStripe\ORM\FieldType\DBTime
  DBVarchar: SilverStripe\ORM\FieldType\DBVarchar
  DBYear: SilverStripe\ORM\FieldType\DBYear
  SS_Datetime: SilverStripe\ORM\FieldType\DBDatetime
  SilverStripe\Model\FieldType\DBBoolean: SilverStripe\ORM\FieldType\DBBoolean
  SilverStripe\Model\FieldType\DBClassName: SilverStripe\ORM\FieldType\DBClassName
  SilverStripe\Model\FieldType\DBComposite: SilverStripe\ORM\FieldType\DBComposite
  SilverStripe\Model\FieldType\DBCurrency: SilverStripe\ORM\FieldType\DBCurrency
  SilverStripe\Model\FieldType\DBDate: SilverStripe\ORM\FieldType\DBDate
  SilverStripe\Model\FieldType\DBDatetime: SilverStripe\ORM\FieldType\DBDatetime
  SilverStripe\Model\FieldType\DBDecimal: SilverStripe\ORM\FieldType\DBDecimal
  SilverStripe\Model\FieldType\DBDouble: SilverStripe\ORM\FieldType\DBDouble
  SilverStripe\Model\FieldType\DBEnum: SilverStripe\ORM\FieldType\DBEnum
  SilverStripe\Model\FieldType\DBField: SilverStripe\ORM\FieldType\DBField
  SilverStripe\Model\FieldType\DBFloat: SilverStripe\ORM\FieldType\DBFloat
  SilverStripe\Model\FieldType\DBForeignKey: SilverStripe\ORM\FieldType\DBForeignKey
  SilverStripe\Model\FieldType\DBHTMLText: SilverStripe\ORM\FieldType\DBHTMLText
  SilverStripe\Model\FieldType\DBHTMLVarchar: SilverStripe\ORM\FieldType\DBHTMLVarchar
  SilverStripe\Model\FieldType\DBInt: SilverStripe\ORM\FieldType\DBInt
  SilverStripe\Model\FieldType\DBLocale: SilverStripe\ORM\FieldType\DBLocale
  SilverStripe\Model\FieldType\DBMoney: SilverStripe\ORM\FieldType\DBMoney
  SilverStripe\Model\FieldType\DBMultiEnum: SilverStripe\ORM\FieldType\DBMultiEnum
  SilverStripe\Model\FieldType\DBPercentage: SilverStripe\ORM\FieldType\DBPercentage
  SilverStripe\Model\FieldType\DBPolymorphicForeignKey: SilverStripe\ORM\FieldType\DBPolymorphicForeignKey
  SilverStripe\Model\FieldType\DBPrimaryKey: SilverStripe\ORM\FieldType\DBPrimaryKey
  SilverStripe\Model\FieldType\DBString: SilverStripe\ORM\FieldType\DBString
  SilverStripe\Model\FieldType\DBText: SilverStripe\ORM\FieldType\DBText
  SilverStripe\Model\FieldType\DBTime: SilverStripe\ORM\FieldType\DBTime
  SilverStripe\Model\FieldType\DBVarchar: SilverStripe\ORM\FieldType\DBVarchar
  SilverStripe\Model\FieldType\DBYear: SilverStripe\ORM\FieldType\DBYear
  SilverStripe\Model\FieldType\SS_Datetime: SilverStripe\ORM\FieldType\DBDatetime
  ChangeSet: SilverStripe\ORM\Versioning\ChangeSet
  ChangeSetItem: SilverStripe\ORM\Versioning\ChangeSetItem
  DataDifferencer: SilverStripe\ORM\Versioning\DataDifferencer
  VersionableExtension: SilverStripe\ORM\Versioning\VersionableExtension
  Versioned: SilverStripe\ORM\Versioning\Versioned
  Versioned_Version: SilverStripe\ORM\Versioning\Versioned_Version
  VersionedGridFieldDetailForm: SilverStripe\ORM\Versioning\VersionedGridFieldDetailForm
  VersionedGridFieldItemRequest: SilverStripe\ORM\Versioning\VersionedGridFieldItemRequest
  Hierarchy: SilverStripe\ORM\Hierarchy\Hierarchy
  Authenticator: SilverStripe\Security\Authenticator
  BasicAuth: SilverStripe\Security\BasicAuth
  ChangePasswordForm: SilverStripe\Security\ChangePasswordForm
  CMSMemberLoginForm: SilverStripe\Security\CMSMemberLoginForm
  CMSSecurity: SilverStripe\Security\CMSSecurity
  Group: SilverStripe\Security\Group
  GroupCsvBulkLoader: SilverStripe\Security\GroupCsvBulkLoader
  LoginAttempt: SilverStripe\Security\LoginAttempt
  LoginForm: SilverStripe\Security\LoginForm
  Member: SilverStripe\Security\Member
  Member_GroupSet: SilverStripe\Security\Member_GroupSet
  Member_Validator: SilverStripe\Security\Member_Validator
  MemberAuthenticator: SilverStripe\Security\MemberAuthenticator
  MemberCsvBulkLoader: SilverStripe\Security\MemberCsvBulkLoader
  MemberLoginForm: SilverStripe\Security\MemberLoginForm
  MemberPassword: SilverStripe\Security\MemberPassword
  PasswordEncryptor: SilverStripe\Security\PasswordEncryptor
  PasswordEncryptor_Blowfish: SilverStripe\Security\PasswordEncryptor_Blowfish
  PasswordEncryptor_PHPHash: SilverStripe\Security\PasswordEncryptor_PHPHash
  PasswordEncryptor_LegacyPHPHash: SilverStripe\Security\PasswordEncryptor_LegacyPHPHash
  PasswordEncryptor_MySQLPassword: SilverStripe\Security\PasswordEncryptor_MySQLPassword
  PasswordEncryptor_MySQLOldPassword: SilverStripe\Security\PasswordEncryptor_MySQLOldPassword
  PasswordEncryptor_None: SilverStripe\Security\PasswordEncryptor_None
  PasswordEncryptor_NotFoundException: SilverStripe\Security\PasswordEncryptor_NotFoundException
  PasswordEncryptor_EncryptionFailed: SilverStripe\Security\PasswordEncryptor_EncryptionFailed
  PasswordValidator: SilverStripe\Security\PasswordValidator
  Permission: SilverStripe\Security\Permission
  Permission_Group: SilverStripe\Security\Permission_Group
  PermissionCheckboxSetField: SilverStripe\Security\PermissionCheckboxSetField
  PermissionCheckboxSetField_Readonly: SilverStripe\Security\PermissionCheckboxSetField_Readonly
  PermissionFailureException: SilverStripe\Security\PermissionFailureException
  PermissionProvider: SilverStripe\Security\PermissionProvider
  PermissionRole: SilverStripe\Security\PermissionRole
  PermissionRoleCode: SilverStripe\Security\PermissionRoleCode
  RandomGenerator: SilverStripe\Security\RandomGenerator
  RememberLoginHash: SilverStripe\Security\RememberLoginHash
  Security: SilverStripe\Security\Security
  SecurityToken: SilverStripe\Security\SecurityToken
  NullSecurityToken: SilverStripe\Security\NullSecurityToken
skipConfigs:
  - db
  - casting
  - table_name
  - fixed_fields
  - menu_title
  - allowed_actions
