// This file was generated by silverstripe/cow from javascript/lang/src/fr.js.
// See https://github.com/tractorcow/cow for details
if(typeof(ss) == 'undefined' || typeof(ss.i18n) == 'undefined') {
	if(typeof(console) != 'undefined') console.error('Class ss.i18n not defined');
} else {
	ss.i18n.addDictionary('fr', {
    "VALIDATOR.FIELDREQUIRED": "Veuillez remplir \"%s\", c'est un champ requis.",
    "HASMANYFILEFIELD.UPLOADING": "Uploading... %s",
    "TABLEFIELD.DELETECONFIRMMESSAGE": "Etes-vous sûr de vouloir supprimer cet enregistrement ?",
    "LOADING": "chargement...",
    "UNIQUEFIELD.SUGGESTED": "Changez la valeur de '%s' : %s",
    "UNIQUEFIELD.ENTERNEWVALUE": "You devez saisir une nouvelle valeur pou ce champ",
    "UNIQUEFIELD.CANNOTLEAVEEMPTY": "Ce champ ne peut être laissé vide",
    "RESTRICTEDTEXTFIELD.CHARCANTBEUSED": "Le character '%s' ne peut être utilisé dans ce champ",
    "UPDATEURL.CONFIRM": "Voulez-vous que je change l'URL en:\n\n%s/\n\nCliquez Ok pour changer l'URL, cliquez Annuler pour la laisser à:\n\n%s",
    "UPDATEURL.CONFIRMURLCHANGED": "The URL has been changed to\n'%s'",
    "FILEIFRAMEFIELD.DELETEFILE": "Delete File",
    "FILEIFRAMEFIELD.UNATTACHFILE": "Un-Attach File",
    "FILEIFRAMEFIELD.DELETEIMAGE": "Delete Image",
    "FILEIFRAMEFIELD.CONFIRMDELETE": "Are you sure you want to delete this file?",
    "LeftAndMain.IncompatBrowserWarning": "Your browser is not compatible with the CMS interface. Please use Internet Explorer 7+, Google Chrome 10+ or Mozilla Firefox 3.5+.",
    "GRIDFIELD.ERRORINTRANSACTION": "Une erreur est survenue durant la transaction avec le serveur\n Merci de reesayer plus tard.",
    "HtmlEditorField.SelectAnchor": "Select an anchor",
    "UploadField.ConfirmDelete": "Are you sure you want to remove this file from the server filesystem?",
    "UploadField.PHP_MAXFILESIZE": "File exceeds upload_max_filesize (php.ini directive)",
    "UploadField.HTML_MAXFILESIZE": "File exceeds MAX_FILE_SIZE (HTML form directive)",
    "UploadField.ONLYPARTIALUPLOADED": "File was only partially uploaded",
    "UploadField.NOFILEUPLOADED": "No File was uploaded",
    "UploadField.NOTMPFOLDER": "Missing a temporary folder",
    "UploadField.WRITEFAILED": "Failed to write file to disk",
    "UploadField.STOPEDBYEXTENSION": "File upload stopped by extension",
    "UploadField.TOOLARGE": "Filesize is too large",
    "UploadField.TOOSMALL": "Filesize is too small",
    "UploadField.INVALIDEXTENSION": "Extension is not allowed",
    "UploadField.MAXNUMBEROFFILESSIMPLE": "Max number of files exceeded",
    "UploadField.UPLOADEDBYTES": "Uploaded bytes exceed file size",
    "UploadField.EMPTYRESULT": "Empty file upload result",
    "UploadField.LOADING": "Loading ...",
    "UploadField.Editing": "Editing ...",
    "UploadField.Uploaded": "Uploaded",
    "UploadField.OVERWRITEWARNING": "File with the same name already exists",
    "TreeDropdownField.ENTERTOSEARCH": "Press enter to search",
    "TreeDropdownField.OpenLink": "Open",
    "TreeDropdownField.FieldTitle": "Choose",
    "TreeDropdownField.SearchFieldTitle": "Choose or Search"
});
}