// This file was generated by silverstripe/cow from javascript/lang/src/bg.js.
// See https://github.com/tractorcow/cow for details
if (typeof(ss) === 'undefined' || typeof(ss.i18n) === 'undefined') {
  if (typeof(console) !== 'undefined') { // eslint-disable-line no-console
    console.error('Class ss.i18n not defined');  // eslint-disable-line no-console
  }
} else {
  ss.i18n.addDictionary('bg', {
    "VALIDATOR.FIELDREQUIRED": "Полето \"%s\" е задължително.",
    "HASMANYFILEFIELD.UPLOADING": "Качване... %s",
    "TABLEFIELD.DELETECONFIRMMESSAGE": "Да бъде ли изтрит този запис?",
    "LOADING": "зареждане...",
    "UNIQUEFIELD.SUGGESTED": "Стойността е променена '%s' : %s",
    "UNIQUEFIELD.ENTERNEWVALUE": "Трябва да въведете валидна стойност в това поле",
    "UNIQUEFIELD.CANNOTLEAVEEMPTY": "Полето не може да остане празно",
    "RESTRICTEDTEXTFIELD.CHARCANTBEUSED": "Символът '%s' не може да бъде използван в това поле",
    "UPDATEURL.CONFIRM": "Would you like me to change the URL to:\n\n%s/\n\nClick Ok to change the URL, click Cancel to leave it as:\n\n%s",
    "UPDATEURL.CONFIRMURLCHANGED": "URL адресът беше сменен на\n'%s'",
    "FILEIFRAMEFIELD.DELETEFILE": "Изтрий файла",
    "FILEIFRAMEFIELD.UNATTACHFILE": "Премахни файла",
    "FILEIFRAMEFIELD.DELETEIMAGE": "Изтрий снимката",
    "FILEIFRAMEFIELD.CONFIRMDELETE": "Да бъде ли изтрит този файл?",
    "LeftAndMain.IncompatBrowserWarning": "Your browser is not compatible with the CMS interface. Please use Internet Explorer 7+, Google Chrome 10+ or Mozilla Firefox 3.5+.",
    "GRIDFIELD.ERRORINTRANSACTION": "Възникна грешка при извличане на данни от сървъра\n Опитайте отново по-късно.",
    "HtmlEditorField.SelectAnchor": "Select an anchor",
    "UploadField.ConfirmDelete": "Този файл ще бъде изтрит от сървъра. Сигурни ли сте?",
    "UploadField.PHP_MAXFILESIZE": "Големината на файла надхвърля upload_max_filesize (php.ini директивата)",
    "UploadField.HTML_MAXFILESIZE": "Големината на файла надхвърле MAX_FILE_SIZE (директива на HTML формата)",
    "UploadField.ONLYPARTIALUPLOADED": "Файлът беше качен частично",
    "UploadField.NOFILEUPLOADED": "Файлът не беше качен",
    "UploadField.NOTMPFOLDER": "Липсва временна папка",
    "UploadField.WRITEFAILED": "Файлът не можа да бъде записан",
    "UploadField.STOPEDBYEXTENSION": "File upload stopped by extension",
    "UploadField.TOOLARGE": "Много голям файл",
    "UploadField.TOOSMALL": "Файлът е много малък",
    "UploadField.INVALIDEXTENSION": "Това разширение не е разрешено",
    "UploadField.MAXNUMBEROFFILESSIMPLE": "Максималния брой файлове е надхвърлен",
    "UploadField.UPLOADEDBYTES": "Uploaded bytes exceed file size",
    "UploadField.EMPTYRESULT": "Empty file upload result",
    "UploadField.LOADING": "Зареждане ...",
    "UploadField.Editing": "Редактиране ...",
    "UploadField.Uploaded": "Качен",
    "UploadField.OVERWRITEWARNING": "Вече съществува файл с това име",
    "TreeDropdownField.ENTERTOSEARCH": "Натисни Enter за търсена",
    "TreeDropdownField.OpenLink": "Отвори",
    "TreeDropdownField.FieldTitle": "Избери",
    "TreeDropdownField.SearchFieldTitle": "Избери или Търси"
});
}