// This file was generated by silverstripe/cow from javascript/lang/src/fi.js.
// See https://github.com/tractorcow/cow for details
if(typeof(ss) == 'undefined' || typeof(ss.i18n) == 'undefined') {
	if(typeof(console) != 'undefined') console.error('Class ss.i18n not defined');
} else {
	ss.i18n.addDictionary('fi', {
    "VALIDATOR.FIELDREQUIRED": "Syötä \"%s\", se on vaadittu tieto.",
    "HASMANYFILEFIELD.UPLOADING": "Ladataan... %s",
    "TABLEFIELD.DELETECONFIRMMESSAGE": "Haluatko varmasti poistaa tämän tietueen?",
    "LOADING": "ladataan...",
    "UNIQUEFIELD.SUGGESTED": "Muutettu arvoksi '%s' : %s",
    "UNIQUEFIELD.ENTERNEWVALUE": "Sinun täytyy syöttää uusi arvo tälle kentälle",
    "UNIQUEFIELD.CANNOTLEAVEEMPTY": "Tätä kenttää ei voi jättää tyhjäksi",
    "RESTRICTEDTEXTFIELD.CHARCANTBEUSED": "Merkkiä '%s' ei voi käyttää tässä kentässä",
    "UPDATEURL.CONFIRM": "Haluatko muuttaa URL:ksi:\n\n%s/\n\nKlikkaa OK muuttaaksesi URL:n, klikkaa Peruuta jättääksesi sen ennalleen:\n\n%s",
    "UPDATEURL.CONFIRMURLCHANGED": "URL on muutettu muotoon\n'%s'",
    "FILEIFRAMEFIELD.DELETEFILE": "Poista tiedosto",
    "FILEIFRAMEFIELD.UNATTACHFILE": "Irroita tiedosto",
    "FILEIFRAMEFIELD.DELETEIMAGE": "Poista kuva",
    "FILEIFRAMEFIELD.CONFIRMDELETE": "Haluatko varmasti poistaa tämän tiedoston?",
    "LeftAndMain.IncompatBrowserWarning": "Selaimesi ei ole yhteensopiva julkaisujärjestelmän kanssa. Käytä Internet Explorer 7+, Google Chrome 10+ tai Mozilla Firefox 3.5+.",
    "GRIDFIELD.ERRORINTRANSACTION": "Tapahtui virhe haettaessa tietoa palvelimelta.\nYritä uudestaan myöhemmin.",
    "HtmlEditorField.SelectAnchor": "Valitse ankkuri",
    "UploadField.ConfirmDelete": "Haluatko varmasti poistaa tämän tiedoston palvelimelta?",
    "UploadField.PHP_MAXFILESIZE": "Tiedostokoko ylittää upload_max_filesize (php.ini directive)",
    "UploadField.HTML_MAXFILESIZE": "Tiedostokoko ylittää MAX_FILE_SIZE (HTML form directive)",
    "UploadField.ONLYPARTIALUPLOADED": "Tiedosto ladattiin vain osittain",
    "UploadField.NOFILEUPLOADED": "Tiedostoa ei ladattu",
    "UploadField.NOTMPFOLDER": "Tilapäinen kansio puuttuu",
    "UploadField.WRITEFAILED": "Tiedoston kirjoittaminen levylle epäonnistui",
    "UploadField.STOPEDBYEXTENSION": "Tiedostolataus keskeytetty laajennoksen toimesta",
    "UploadField.TOOLARGE": "Tiedostokoko on liian suuri",
    "UploadField.TOOSMALL": "Tiedostokoko on liian pieni",
    "UploadField.INVALIDEXTENSION": "Tiedostopääte ei ole sallittu",
    "UploadField.MAXNUMBEROFFILESSIMPLE": "Suurin sallittu määrä tiedostoja ylitetty.",
    "UploadField.UPLOADEDBYTES": "Ladatut tavut ylittävät tiedostokoon",
    "UploadField.EMPTYRESULT": "Tiedostolatauksen tulos tyhjä",
    "UploadField.LOADING": "Ladataan...",
    "UploadField.Editing": "Muokataan ...",
    "UploadField.Uploaded": "Ladattu",
    "UploadField.OVERWRITEWARNING": "Samanniminen tiedosto on jo palvelimella",
    "TreeDropdownField.ENTERTOSEARCH": "Paina Enter suorittaaksesi haun",
    "TreeDropdownField.OpenLink": "Avaa",
    "TreeDropdownField.FieldTitle": "Valitse",
    "TreeDropdownField.SearchFieldTitle": "Valitse tai Hae"
});
}