// This file was generated by GenerateJavaScriptI18nTask from javascript/lang/src/ja.js.
// See https://github.com/silverstripe/silverstripe-buildtools for details
if(typeof(ss) == 'undefined' || typeof(ss.i18n) == 'undefined') {
	if(typeof(console) != 'undefined') console.error('Class ss.i18n not defined');
} else {
	ss.i18n.addDictionary('ja', {
    "HASMANYFILEFIELD.UPLOADING": "アップロード中です... %s",
    "UploadField.NOFILEUPLOADED": "ファイルはアップロードされませんでした．",
    "UploadField.Uploaded": "アップロードしました．",
    "UploadField.TOOSMALL": "ファイルサイズが小さすぎます．",
    "HtmlEditorField.SelectAnchor": "アンカーを選択する",
    "UploadField.MAXNUMBEROFFILESSIMPLE": "ファイルの最大数を超えました．",
    "UploadField.ConfirmDelete": "サーバーのファイルシステムからこのファイルを本当に削除しても良いですか?",
    "UploadField.NOTMPFOLDER": "一時フォルダがありません．",
    "RESTRICTEDTEXTFIELD.CHARCANTBEUSED": "文字'%s'はこのフィールドでは利用することができません．",
    "UploadField.UPLOADEDBYTES": "アップロードされたバイトはファイルサイズを超えました．",
    "VALIDATOR.FIELDREQUIRED": "\"%s\"を入力してください，必須項目です．",
    "UploadField.HTML_MAXFILESIZE": "MAX_FILE_SIZE(最大ファイルサイズ)をファイルが超えています．(HTMLフォームで指定されています)",
    "UploadField.PHP_MAXFILESIZE": "upload_max_filesize(最大アップロードファイルサイズ)をファイルが超えています．(php.iniで指定されています)",
    "UploadField.TOOLARGE": "ファイルサイズが大きすぎます．",
    "UNIQUEFIELD.CANNOTLEAVEEMPTY": "このフィールドは空にすることができません．",
    "UNIQUEFIELD.ENTERNEWVALUE": "このフィールドに新しい値を入力する必要があります．",
    "UploadField.WRITEFAILED": "ディスクへのファイル書き込みに失敗しました．",
    "UploadField.ONLYPARTIALUPLOADED": "ファイルは部分的にアップロードされました．",
    "UploadField.STOPEDBYEXTENSION": "拡張子によりファイルアップロードが停止しました．",
    "TreeDropdownField.FieldTitle": "選択する",
    "FILEIFRAMEFIELD.DELETEIMAGE": "画像を削除",
    "LeftAndMain.IncompatBrowserWarning": "ご利用のブラウザはCMSのインターフェイスと互換性がありません．Internet Explorer 7以上, Google Chrome 10以上またはMozilla Firefox 3.5以上をご利用ください",
    "UploadField.Editing": "編集中...",
    "TreeDropdownField.OpenLink": "開く",
    "TreeDropdownField.SearchFieldTitle": "選択または検索",
    "UploadField.INVALIDEXTENSION": "拡張子は許可されていません．",
    "LOADING": "読み込み中...",
    "FILEIFRAMEFIELD.UNATTACHFILE": "Un-Attach File",
    "FILEIFRAMEFIELD.CONFIRMDELETE": "このファイルを本当に削除しても良いですか?",
    "UNIQUEFIELD.SUGGESTED": "'%s'へ値を変更しました : %s",
    "TABLEFIELD.DELETECONFIRMMESSAGE": "このレコードを本当に削除しますか?",
    "UPDATEURL.CONFIRM": "URLを次へ変更しますか?:\n\n%s/\n\nOKをクリックするとURLが変更されます．キャンセルをクリックするとURLは保持されます:\n\n%s",
    "UploadField.EMPTYRESULT": "Empty file upload result",
    "TreeDropdownField.ENTERTOSEARCH": "Enterキーを押して検索する",
    "FILEIFRAMEFIELD.DELETEFILE": "ファイルを削除",
    "UploadField.LOADING": "読み込み中...",
    "GRIDFIELD.ERRORINTRANSACTION": "サーバーからデータを取得中にエラーが発生しました．\n 後ほど改めてお試しください．",
    "UPDATEURL.CONFIRMURLCHANGED": "URLは次へ変更されました\n\"%s\"",
    "UploadField.OVERWRITEWARNING": "このファイル名はすでに存在します"
});
}