// This file was generated by silverstripe/cow from javascript/lang/src/sr@latin.js.
// See https://github.com/tractorcow/cow for details
if (typeof(ss) === 'undefined' || typeof(ss.i18n) === 'undefined') {
  if (typeof(console) !== 'undefined') { // eslint-disable-line no-console
    console.error('Class ss.i18n not defined');  // eslint-disable-line no-console
  }
} else {
  ss.i18n.addDictionary('sr@latin', {
    "FILEIFRAMEFIELD.CONFIRMDELETE": "Da li ste sigurni da želite da izbrišete ovu datoteku?",
    "FILEIFRAMEFIELD.DELETEFILE": "Izbriši datoteku",
    "FILEIFRAMEFIELD.DELETEIMAGE": "Izbriši sliku",
    "FILEIFRAMEFIELD.UNATTACHFILE": "Otkači datoteku",
    "File.DRAFT": "Draft",
    "File.MODIFIED": "Modified",
    "File.PUBLISHED": "Published",
    "FormField.NONE": "None",
    "GRIDFIELD.ERRORINTRANSACTION": "Prilikom preuzimanja podataka sa servera došlo je do greške.\nPokušajte ponovo kasnije.",
    "HASMANYFILEFIELD.UPLOADING": "Postavljanje... %s",
    "HtmlEditorField.SelectAnchor": "Izaberi sidro",
    "LOADING": "Učitavanje...",
    "LeftAndMain.IncompatBrowserWarning": "Vaš veb pregledač nije kompatibilan sa interfejsom CMS-a. Molimo Vas da koristite Internet Explorer 7+, Google Chrome 10+ ili Mozilla Firefox 3.5+.",
    "RESTRICTEDTEXTFIELD.CHARCANTBEUSED": "Znak '%s' ne možete koristiti u ovom polju",
    "TABLEFIELD.DELETECONFIRMMESSAGE": "Da li ste sigurni da želite da izbrišete ovaj zapis?",
    "TreeDropdownField.ENTERTOSEARCH": "Pritisnite Enter za pretraživanje",
    "TreeDropdownField.FieldTitle": "Izaberi",
    "TreeDropdownField.OpenLink": "Otvori",
    "TreeDropdownField.SearchFieldTitle": "Izaberi ili Pronađi",
    "UNIQUEFIELD.CANNOTLEAVEEMPTY": "Ovo polje ne sme biti prazno",
    "UNIQUEFIELD.ENTERNEWVALUE": "Morate unesti novu vrednost za ovo polje",
    "UNIQUEFIELD.SUGGESTED": "Promenjena vrednost na '%s' : %s",
    "UPDATEURL.CONFIRM": "Da li želite da promenim URL na:\n\n\n%s/\n\nKlikni na U redu da bi URL bio promenjen, klikni na Odustani da bi ostalo:\n\n%s",
    "UPDATEURL.CONFIRMURLCHANGED": "URL je promenjen na\n'%s'",
    "UploadField.ConfirmDelete": "Da li ste sigurni da želite da izbrišete ovu datoteku sa datotečkog sistema servera?",
    "UploadField.EMPTYRESULT": "Rezultat postavljanja je prazna datoteka",
    "UploadField.Editing": "Uređivanje...",
    "UploadField.HTML_MAXFILESIZE": "Datoteka premašuje MAX_FILE_SIZE (HTML direktiva obrazaca)",
    "UploadField.INVALIDEXTENSION": "Ekstenzija nije dozvoljena",
    "UploadField.LOADING": "Učitavanje...",
    "UploadField.MAXNUMBEROFFILESSIMPLE": "Maksimalan broj datoteka je premašen",
    "UploadField.NOFILEUPLOADED": "Ni jedna datoteka nije postavljena",
    "UploadField.NOTMPFOLDER": "Nedostaje privremena fascikla",
    "UploadField.ONLYPARTIALUPLOADED": "Datoteka je samo delimično postavljena",
    "UploadField.OVERWRITEWARNING": "Datoteka sa istim imenom već postoji",
    "UploadField.PHP_MAXFILESIZE": "Datoteka premašuje upload_max_filesize (php.ini direktiva)",
    "UploadField.STOPEDBYEXTENSION": "Postavljanje datoteke je zaustavnjeno za ekstenziju",
    "UploadField.TOOLARGE": "Datoteka je prevelika",
    "UploadField.TOOSMALL": "Datoteka je premala",
    "UploadField.UPLOADEDBYTES": "Postavljeni bajtovi premašuju veličinu datoteke",
    "UploadField.Uploaded": "Postavljeno",
    "UploadField.WRITEFAILED": "Upisivanje datoteke na disk nije uspelo",
    "VALIDATOR.FIELDREQUIRED": "Molimo Vas da popunite \"%s\", obavezno je."
});
}