export const ACTION_TYPES = {
  ADD_FORM: 'ADD_FORM',
  REMOVE_FORM: 'REMOVE_FORM',
  SUBMIT_FORM_FAILURE: 'SUBMIT_FORM_FAILURE',
  SUBMIT_FORM_REQUEST: 'SUBMIT_FORM_REQUEST',
  SUBMIT_FORM_SUCCESS: 'SUBMIT_FORM_SUCCESS',
  UPDATE_FIELD: 'UPDATE_FIELD',
  SET_SUBMIT_ACTION: 'SET_SUBMIT_ACTION',
};
