jobs:
  include:
    - php: 7.1
      env:
        - DB=MYSQL
        - PHPCS_TEST=1
        - PHPUNIT_TEST=1
        - GENERAL_RECIPE_VERSION="$GENERAL_RECIPE_EARLIEST_MINOR_VERSION"
        - COMPOSER_ARG=--prefer-lowest
    - php: 7.4
      env:
        - DB=PGSQL
        - PHPUNIT_TEST=1
        - GENERAL_RECIPE_VERSION="$GENERAL_RECIPE_LATEST_MINOR_VERSION"
    - php: nightly
      env: 
        - DB=MYSQL
        - PHPUNIT_TEST=1
        - COMPOSER_ARG=--ignore-platform-reqs
        - GENERAL_RECIPE_VERSION="$GENERAL_RECIPE_MAJOR_VERSION"
