---
name: databaseconnectors
---
SilverStripe\Core\Injector\Injector:
  MySQLDatabase:
    class: 'SilverStripe\ORM\Connect\MySQLDatabase'
    properties:
      connector: '%$MySQLiConnector'
      schemaManager: '%$MySQLSchemaManager'
      queryBuilder: '%$MySQLQueryBuilder'
  MySQLiConnector:
    class: 'SilverStripe\ORM\Connect\MySQLiConnector'
    type: prototype
  MySQLSchemaManager:
    class: 'SilverStripe\ORM\Connect\MySQLSchemaManager'
  MySQLQueryBuilder:
    class: 'SilverStripe\ORM\Connect\MySQLQueryBuilder'
