---
Name: DevelopmentAdmin
---
DevelopmentAdmin:
  registered_controllers:
    build:
      controller: 'DevBuildController'
      links:
        build: 'Build/rebuild this environment. Call this whenever you have updated your project sources'
    tasks:
      controller: 'TaskRunner'
      links:
        tasks: 'See a list of build tasks to run'
