export default {
    CREATE_CAMPAIGN: 'CREATE_CAMPAIGN',
    UPDATE_CAMPAIGN: 'UPDATE_CAMPAIGN',
    DELETE_CAMPAIGN: 'DELETE_CAMPAIGN',
    FETCH_CAMPAIGN_REQUEST: 'FETCH_CAMPAIGN_REQUEST',
    FETCH_CAMPAIGN_FAILURE: 'FETCH_CAMPAIGN_FAILURE',
    FETCH_CAMPAIGN_SUCCESS: 'FETCH_CAMPAIGN_SUCCESS'
};
