<?php


namespace SilverStripe\ORM\Tests\EagerLoading\DataListEagerLoaderTest;


use SilverStripe\ORM\DataQuery;
use SilverStripe\ORM\NaiveDataQueryExecutor;

class DebuggableNaiveDataQueryExecutor extends NaiveDataQueryExecutor
{
    protected $queries = 0;

    public function execute(DataQuery $dataQuery, ?string $modifier = null): iterable
    {
        $this->queries++;
        return parent::execute($dataQuery, $modifier); // TODO: Change the autogenerated stub
    }

    public function getFirstRow(DataQuery $dataQuery): iterable
    {
        $this->queries++;
        return parent::getFirstRow($dataQuery); // TODO: Change the autogenerated stub
    }

    public function getLastRow(DataQuery $dataQuery): iterable
    {
        $this->queries++;
        return parent::getLastRow($dataQuery);
    }

    public function getCount(DataQuery $dataQuery): string
    {
        $this->queries++;
        return parent::getCount($dataQuery);
    }

    public function reset()
    {
        $this->queries = 0;
    }

    public function getQueries(): int
    {
        return $this->queries;
    }

}