// This file was generated by GenerateJavaScriptI18nTask from javascript/lang/src/pl.js.
// See https://github.com/silverstripe/silverstripe-buildtools for details
if(typeof(ss) == 'undefined' || typeof(ss.i18n) == 'undefined') {
	if(typeof(console) != 'undefined') console.error('Class ss.i18n not defined');
} else {
	ss.i18n.addDictionary('pl', {
    "LeftAndMain.CONFIRMUNSAVED": "Czy na pewno chcesz kontynuować nawigację poza tą stronę?\n\nUWAGA: Twoje zmiany nie zostały zapisane.\n\nWciśnij OK aby kontynuować, wciśnij Anuluj aby pozostać na tej stronie.",
    "LeftAndMain.CONFIRMUNSAVEDSHORT": "UWAGA: Twoje zmiany nie zostały zapisane.",
    "SecurityAdmin.BATCHACTIONSDELETECONFIRM": "Czy na pewno chcesz usunąć %s grup?",
    "ModelAdmin.SAVED": "Zapisano",
    "ModelAdmin.REALLYDELETE": "Na pewno usunąć?",
    "ModelAdmin.DELETED": "Usunięto",
    "ModelAdmin.VALIDATIONERROR": "Niepoprawne dane",
    "LeftAndMain.PAGEWASDELETED": "Ta strona została usunięta. Wybierz stronę z listy aby rozpocząć edycję."
});
}