// This file was generated by GenerateJavaScriptI18nTask from javascript/lang/src/ro.js.
// See https://github.com/silverstripe/silverstripe-buildtools for details
if(typeof(ss) == 'undefined' || typeof(ss.i18n) == 'undefined') {
	if(typeof(console) != 'undefined') console.error('Class ss.i18n not defined');
} else {
	ss.i18n.addDictionary('ro', {
    "LeftAndMain.CONFIRMUNSAVED": "Sunteți sigur că doriți să părăsiți pagina?\n\nAVERTISMENT: Modificările nu au fost salvate.\n\nApăsați OK pentru a continua, sau Anulați pentru a rămâne pe pagina curentă.",
    "LeftAndMain.CONFIRMUNSAVEDSHORT": "AVERTISMENT: Modificările nu au fost salvate.",
    "SecurityAdmin.BATCHACTIONSDELETECONFIRM": "Sigur doriți să ștergeți grupurile %s?",
    "ModelAdmin.SAVED": "Salvat",
    "ModelAdmin.REALLYDELETE": "Sigur doriți să ștergeți?",
    "ModelAdmin.DELETED": "Șters",
    "ModelAdmin.VALIDATIONERROR": "Eroare de validare",
    "LeftAndMain.PAGEWASDELETED": "Această pagină a fost ștearsă. Pentru a edita pagina, selectați-o din stânga."
});
}