// This file was generated by silverstripe/cow from admin/javascript/lang/src/sk.js.
// See https://github.com/tractorcow/cow for details
if (typeof(ss) === 'undefined' || typeof(ss.i18n) === 'undefined') {
  if (typeof(console) !== 'undefined') { // eslint-disable-line no-console
    console.error('Class ss.i18n not defined');  // eslint-disable-line no-console
  }
} else {
  ss.i18n.addDictionary('sk', {
    "CMSMAIN.BATCH_ARCHIVE_PROMPT": "Vybrali ste {num} stránok.\n\nUrčite chcete archivovať tieto stránky?\n\nTieto stránky a jej všetky podstránky budú nezverejnené a odoslané do archívu.",
    "CMSMAIN.BATCH_DELETELIVE_PROMPT": "Máte vybratých {num} stránok.\n\nSkutočne chcete tieto stránky vymazať z webu?",
    "CMSMAIN.BATCH_DELETE_PROMPT": "You have {num} page(s) selected.\n\nDo you really want to delete?",
    "CMSMAIN.BATCH_PUBLISH_PROMPT": "Máte vybratých {num} stránok.\n\nSkutočne ich chcete zverejniť?",
    "CMSMAIN.BATCH_RESTORE_PROMPT": "Vybrali ste {num} stránok.\n\nSkutočne chcete obnoviť?\n\nPodstránky archivovaných stránok budú obnovené do najvyššej úrovne, pokiaľ tieto stránky budú tiež obnovené.",
    "CMSMAIN.BATCH_UNPUBLISH_PROMPT": "Máte vybratých {num} stránok.\n\nSkutočne ich chcete nezverejniť?",
    "CMSMAIN.SELECTONEPAGE": "Prosím, vyberte najmenej 1 stránku",
    "Campaigns.ADDCAMPAIGN": "Pridať kampaň",
    "Campaigns.ITEM_SUMMARY_PLURAL": "%s položiek",
    "Campaigns.ITEM_SUMMARY_SINGULAR": "%s položka",
    "Campaigns.PUBLISHCAMPAIGN": "Zverejniť kampaň",
    "Campaigns.REVERTCAMPAIGN": "Prepnúť",
    "File.NO_SIZE": "N/A",
    "FormBuilderModal.CLOSE": "Close",
    "LeftAndMain.CONFIRMUNSAVED": "Určite chcete opustiť navigáciu z tejto stránky?\n\nUPOZORNENIE: Vaše zmeny neboli uložené.\n\nStlačte OK pre pokračovať, alebo Cancel, ostanete na teto stránke.",
    "LeftAndMain.CONFIRMUNSAVEDSHORT": "UPOZORNENIE: Vaše zmeny neboli uložené.",
    "LeftAndMain.JOIN": ",",
    "LeftAndMain.JOINLAST": "and",
    "LeftAndMain.PAGEWASDELETED": "Táto stránka bola zmazaná. Pre editáciu stránky, vyberte ju vľavo.",
    "LeftAndMain.SEARCHCLEARRESULTS": "Clear search",
    "LeftAndMain.SEARCHRESULTS": "Search results",
    "LeftAndMain.SEARCHRESULTSMESSAGE": "Search results {parts}",
    "LeftAndMain.SEARCHRESULTSMESSAGECATEGORY": "categorised as '{AppCategory}'",
    "LeftAndMain.SEARCHRESULTSMESSAGEEDITEDBETWEEN": "edited between '{CreatedFrom}' to '{CreatedTo}'",
    "LeftAndMain.SEARCHRESULTSMESSAGEEDITEDFROM": "edited from '{CreatedFrom}'",
    "LeftAndMain.SEARCHRESULTSMESSAGEEDITEDTO": "edited before '{CreatedTo}'",
    "LeftAndMain.SEARCHRESULTSMESSAGEKEYWORDS": "with keywords '{Name}'",
    "LeftAndMain.SEARCHRESULTSMESSAGELIMIT": "limited to the folder '{Folder}'",
    "ModelAdmin.DELETED": "Zmazané",
    "ModelAdmin.REALLYDELETE": "Skutočně chcete zmazať?",
    "ModelAdmin.SAVED": "Uložené",
    "ModelAdmin.VALIDATIONERROR": "Chyba platnosti",
    "SecurityAdmin.BATCHACTIONSDELETECONFIRM": "Skutočne chcete zmazať % skupiny?"
});
}