// This file was generated by silverstripe/cow from admin/javascript/lang/src/sl.js.
// See https://github.com/tractorcow/cow for details
if (typeof(ss) === 'undefined' || typeof(ss.i18n) === 'undefined') {
  if (typeof(console) !== 'undefined') { // eslint-disable-line no-console
    console.error('Class ss.i18n not defined');  // eslint-disable-line no-console
  }
} else {
  ss.i18n.addDictionary('sl', {
    "CMSMAIN.BATCH_ARCHIVE_PROMPT": "You have {num} page(s) selected.\n\nAre you sure you want to archive these pages?\n\nThese pages and all of their children pages will be unpublished and sent to the archive.",
    "CMSMAIN.BATCH_DELETELIVE_PROMPT": "You have {num} page(s) selected.\n\nDo you really want to delete these pages from live?",
    "CMSMAIN.BATCH_DELETE_PROMPT": "You have {num} page(s) selected.\n\nDo you really want to delete?",
    "CMSMAIN.BATCH_PUBLISH_PROMPT": "You have {num} page(s) selected.\n\nDo you really want to publish?",
    "CMSMAIN.BATCH_RESTORE_PROMPT": "You have {num} page(s) selected.\n\nDo you really want to restore to stage?\n\nChildren of archived pages will be restored to the root level, unless those pages are also being restored.",
    "CMSMAIN.BATCH_UNPUBLISH_PROMPT": "You have {num} page(s) selected.\n\nDo you really want to unpublish",
    "CMSMAIN.SELECTONEPAGE": "Please select at least one page",
    "Campaigns.ADDCAMPAIGN": "Add campaign",
    "Campaigns.ITEM_SUMMARY_PLURAL": "%s items",
    "Campaigns.ITEM_SUMMARY_SINGULAR": "%s item",
    "Campaigns.PUBLISHCAMPAIGN": "Publish campaign",
    "Campaigns.REVERTCAMPAIGN": "Revert",
    "File.NO_SIZE": "N/A",
    "FormBuilderModal.CLOSE": "Close",
    "LeftAndMain.CONFIRMUNSAVED": "Res želite zapusitit stran?\n\nOPOZORILO: spremembe niso bile shranjene\n\nKliknite OK za nadaljevanje ali Prekliči, da ostanete na trenutni strani.",
    "LeftAndMain.CONFIRMUNSAVEDSHORT": "OPOZORILO: spremembe niso bile shranjene.",
    "LeftAndMain.JOIN": ",",
    "LeftAndMain.JOINLAST": "and",
    "LeftAndMain.PAGEWASDELETED": "Stran je bila izbrisana. Za urejanje izberite stran na levi.",
    "LeftAndMain.SEARCHCLEARRESULTS": "Clear search",
    "LeftAndMain.SEARCHRESULTS": "Search results",
    "LeftAndMain.SEARCHRESULTSMESSAGE": "Search results {parts}",
    "LeftAndMain.SEARCHRESULTSMESSAGECATEGORY": "categorised as '{AppCategory}'",
    "LeftAndMain.SEARCHRESULTSMESSAGEEDITEDBETWEEN": "edited between '{CreatedFrom}' to '{CreatedTo}'",
    "LeftAndMain.SEARCHRESULTSMESSAGEEDITEDFROM": "edited from '{CreatedFrom}'",
    "LeftAndMain.SEARCHRESULTSMESSAGEEDITEDTO": "edited before '{CreatedTo}'",
    "LeftAndMain.SEARCHRESULTSMESSAGEKEYWORDS": "with keywords '{Name}'",
    "LeftAndMain.SEARCHRESULTSMESSAGELIMIT": "limited to the folder '{Folder}'",
    "ModelAdmin.DELETED": "Izbrisano",
    "ModelAdmin.REALLYDELETE": "Izbrišem?",
    "ModelAdmin.SAVED": "Shranjeno",
    "ModelAdmin.VALIDATIONERROR": "Napaka pri preverjanju",
    "SecurityAdmin.BATCHACTIONSDELETECONFIRM": "Izbrišem %s skupin?"
});
}