// This file was generated by GenerateJavaScriptI18nTask from javascript/lang/src/zh.js.
// See https://github.com/silverstripe/silverstripe-buildtools for details
if(typeof(ss) == 'undefined' || typeof(ss.i18n) == 'undefined') {
	if(typeof(console) != 'undefined') console.error('Class ss.i18n not defined');
} else {
	ss.i18n.addDictionary('zh', {
    "LeftAndMain.CONFIRMUNSAVED": "您确定要离开此页面？\n警告：您所做的更改尚未保存。\n请按“确定”继续，或“取消”留在当前页面。\n",
    "LeftAndMain.CONFIRMUNSAVEDSHORT": "警告：您所做的更改尚未保存。",
    "SecurityAdmin.BATCHACTIONSDELETECONFIRM": "您真的要删除 %s 小组吗？",
    "ModelAdmin.SAVED": "已保存",
    "ModelAdmin.REALLYDELETE": "您真的要删除吗？",
    "ModelAdmin.DELETED": "已删除",
    "ModelAdmin.VALIDATIONERROR": "验证错误",
    "LeftAndMain.PAGEWASDELETED": "该页面已被删除。若要编辑一个页面，请在左边选择。"
});
}