name: CI

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  ci:
    name: CI
    # Do not run if this is a pull-request from same repo i.e. not a fork repo
    if: github.event_name != 'pull_request' || github.event.pull_request.head.repo.full_name != github.repository
    uses: silverstripe/gha-ci/.github/workflows/ci.yml@v2
    with:
      # Turn phpcoverage off because it causes a segfault
      phpcoverage_force_off: true
      phpunit_skip_suites: framework-cache-only
      # Ensure we test all in-memory cache factories provided in core
      extra_jobs: |
        - phpunit: true
          phpunit_suite: framework-cache-only
          install_in_memory_cache_exts: true
