name: CI

on:
  push:
  pull_request:
  workflow_dispatch:
  # Every Tuesday at 2:20pm UTC
  schedule:
    - cron: '20 14 * * 2'

jobs:
  ci:
    name: CI
    # Only run cron on the silverstripe account
    if: (github.event_name == 'schedule' && github.repository_owner == 'silverstripe') || (github.event_name != 'schedule')
    uses: silverstripe/gha-ci/.github/workflows/ci.yml@v1
    with:
      # Turn phpcoverage off because it causes a segfault
      phpcoverage_force_off: true
